seed: 11711
use_cuda: True

data:
  sst_dataset:
    train_path: 'data/ids-sst-train.csv'
    val_path: 'data/ids-sst-dev.csv'
    test_path: 'data/ids-sst-test-student.csv'
  quora_dataset:
    train_path: 'data/quora-train.csv'
    val_path: 'data/quora-dev.csv'
    test_path: 'data/quora-test-student.csv'
  sts_dataset:
    train_path: 'data/sts-train.csv'
    val_path: 'data/sts-dev.csv'
    test_path: 'data/sts-test-student.csv'

  dataloader:
    batch_size: 64
    num_workers: 1

bert_model:
  hidden_size: 768
  dropout_prob: 0.1
  mode: 'finetune' # 'pretrain' or 'finetune'
  local_files_only: True
  weigths_path: 'checkpoints/finetune_classifier.pt'

train:
  n_epochs: 10
  lr: 0.00001
  checkpoint_path: 'checkpoints/finetune_classifier.pt'
  dataloader_mode: 'sequential' # 'exhaust' or 'sequential' or 'min' or 'continuos'
  skip_train_eval: 5 # number of times to skip evaluation of train datasets


predict:
  sst_prediction_path: 'predictions/sst_prediction.csv'
  quora_prediction_path: 'predictions/quora_prediction.csv'
  sts_prediction_path: 'predictions/sts_prediction.csv'
